# Generated by Django 5.2.17 on 2026-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pierwsza_lekcja', models.DateTimeField(verbose_name='data i godzina 1. lekcji')),
                ('przedmiot', models.CharField(max_length=100, verbose_name='przedmiot')),
                ('poziom', models.CharField(max_length=50, verbose_name='poziom')),
                ('szkola', models.CharField(max_length=150, verbose_name='szkoła')),
                ('imie_ucznia', models.CharField(max_length=100, verbose_name='imię ucznia')),
                ('nazwisko_rodzica', models.CharField(max_length=100, verbose_name='nazwisko (rodzica)')),
                ('rodzic', models.CharField(max_length=150, verbose_name='rodzic (imię i nazwisko)')),
                ('telefon_glowny', models.CharField(max_length=20, verbose_name='telefon główny')),
                ('email_glowny', models.EmailField(max_length=254, verbose_name='email główny')),
                ('telefon_dodatkowy', models.CharField(blank=True, max_length=20, verbose_name='telefon dodatkowy')),
                ('email_dodatkowy', models.EmailField(blank=True, max_length=254, verbose_name='email dodatkowy')),
                ('korepetytor', models.CharField(max_length=150, verbose_name='korepetytor')),
                ('notatka_od_rodzica', models.TextField(blank=True, verbose_name='notatka od rodzica')),
                ('kto_umowil', models.CharField(max_length=150, verbose_name='kto umówił')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
            ],
            options={
                'verbose_name': 'uczeń',
                'verbose_name_plural': 'uczniowie',
                'ordering': ['-pierwsza_lekcja'],
            },
        ),
    ]
