# Generated by Django 5.2.17 on 2026-09-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_uczen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
            ],
            options={
                'verbose_name': 'nauczyciel',
                'verbose_name_plural': 'nauczyciele',
                'ordering': ['nazwisko'],
            },
        ),
        migrations.RemoveField(
            model_name='uczen',
            name='szkola',
        ),
        migrations.AlterField(
            model_name='uczen',
            name='telefon_dodatkowy',
            field=models.CharField(max_length=20, verbose_name='telefon dodatkowy'),
        ),
        migrations.CreateModel(
            name='Dostepnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('godzina_od', models.TimeField(verbose_name='godzina od')),
                ('godzina_do', models.TimeField(verbose_name='godzina do')),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostepnosci', to='konta.nauczyciel', verbose_name='nauczyciel')),
            ],
            options={
                'verbose_name': 'dostępność',
                'verbose_name_plural': 'dostępności',
                'ordering': ['data', 'godzina_od'],
            },
        ),
    ]
