# Generated by Django 5.2.17 on 2026-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0003_nauczyciel_remove_uczen_szkola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauczyciel',
            name='przedmiot',
            field=models.CharField(choices=[('matematyka', 'matematyka'), ('fizyka', 'fizyka'), ('angielski', 'angielski'), ('chemia', 'chemia'), ('biologia', 'biologia'), ('geografia', 'geografia'), ('polski', 'polski'), ('historia', 'historia')], default='', max_length=100, verbose_name='przedmiot'),
        ),
    ]
