# Generated by Django 5.2.17 on 2026-09-30 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0004_nauczyciel_przedmiot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostepnosc',
            options={'ordering': ['data_od', 'godzina_od'], 'verbose_name': 'dostępność', 'verbose_name_plural': 'dostępności'},
        ),
        migrations.RemoveField(
            model_name='dostepnosc',
            name='data',
        ),
        migrations.AddField(
            model_name='dostepnosc',
            name='data_do',
            field=models.DateField(default=datetime.date(2026, 1, 1), verbose_name='data do'),
        ),
        migrations.AddField(
            model_name='dostepnosc',
            name='data_od',
            field=models.DateField(default=datetime.date(2026, 1, 1), verbose_name='data od'),
        ),
    ]
