# Generated by Django 5.2.17 on 2026-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0005_alter_dostepnosc_options_remove_dostepnosc_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportPlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zawartosc', models.TextField(verbose_name='zawartość raportu')),
                ('email_odbiorcy', models.EmailField(max_length=254, verbose_name='email odbiorcy')),
                ('wyslal', models.CharField(max_length=150, verbose_name='wysłał')),
                ('wyslano', models.DateTimeField(auto_now_add=True, verbose_name='data wysłania')),
            ],
            options={
                'verbose_name': 'raport płatności',
                'verbose_name_plural': 'raporty płatności',
                'ordering': ['-wyslano'],
            },
        ),
        migrations.AddField(
            model_name='uczen',
            name='szkola',
            field=models.CharField(default='', max_length=150, verbose_name='szkoła'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uczen',
            name='zaplacone',
            field=models.BooleanField(default=False, verbose_name='zapłacone'),
        ),
    ]
