# Generated by Django 5.2.17 on 2026-10-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0006_raportplatnosci_uczen_szkola_uczen_zaplacone'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauczyciel',
            name='stawka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='stawka'),
        ),
    ]
