# Generated by Django 5.2.17 on 2026-10-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0007_nauczyciel_stawka'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauczyciel',
            name='ma_umowe',
            field=models.BooleanField(default=False, verbose_name='ma umowę'),
        ),
    ]
