# Generated by Django 5.2.17 on 2026-10-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0008_nauczyciel_ma_umowe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data i godzina lekcji')),
                ('dodano', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lekcje', to='konta.uczen', verbose_name='uczeń')),
            ],
            options={
                'verbose_name': 'lekcja',
                'verbose_name_plural': 'lekcje',
                'ordering': ['data'],
            },
        ),
    ]
